### PR TITLE
Updated installation instructions.

### PR DESCRIPTION
**Pull request by JaydenBischoff**

### CODE REVIEW

**Comment by JaydenBischoff** [comment]
@liconway What error do you get from that command? I tried it in Linux and Windows and I didn't get any.

**Review by JensVarughese — APPROVED** [review]
Looks good to me!

**Comment by Dillonsd** [comment]
> @liconway What error do you get from that command? I tried it in Linux and Windows and I didn't get any.

I think global npm installs do require superuser privileges. Not sure if it's a good idea to encourage that though, I think npm install runs some post/pre-install scripts that could potentially be harmful. I think we talked about using nvm right?

**Comment by JaydenBischoff** [comment]
> > @liconway What error do you get from that command? I tried it in Linux and Windows and I didn't get any.
> 
> I think global npm installs do require superuser privileges. Not sure if it's a good idea to encourage that though, I think npm install runs some post/pre-install scripts that could potentially be harmful. I think we talked about using nvm right?

Yes we are using nvm for installing node. I will have to see if you can install angular using nvm but in the case that you can't, would `npm install @angular/cli` work then?

**Pull request merged**
